# Generated by Django 4.1.3 on 2022-11-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="blog.author",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
