# Generated by Django 4.1.3 on 2022-11-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_author"),
    ]

    operations = [
        migrations.DeleteModel(name="Author",),
    ]
