# Generated by Django 3.2.5 on 2022-05-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220531_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityroutine',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.place'),
        ),
    ]
