# Generated by Django 3.0.3 on 2020-07-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200725_1315'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='User',
        ),
    ]
