# Generated by Django 3.0.3 on 2020-07-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200725_1315'),
        ('accounts', '0002_auto_20200725_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
