# Generated by Django 2.2.7 on 2020-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200725_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='adhar',
            field=models.IntegerField(unique=True, verbose_name='adhar number'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(verbose_name='phone number'),
        ),
    ]
