# Generated by Django 3.0.3 on 2020-08-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200805_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='description',
        ),
    ]
