# Generated by Django 2.2.7 on 2020-08-11 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_score_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='source_file',
            field=models.FileField(upload_to='home/files'),
        ),
    ]
