# Generated by Django 4.1.3 on 2023-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='data_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
