# Generated by Django 4.1.3 on 2023-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_data_time_flight_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seat_count',
            field=models.IntegerField(default=60),
        ),
    ]
